version: "3"

services:
  app:
    container_name: "client.seinfeld"
    image: "khemlabs/seinfeld-shuffle:${TAG:-latest}"
    env_file: "./.env.docker"
    build:
      context: ./

networks:
  default:
    external:
      name: client-seinfeld
